export const dataUser = [
    { 
        id: 1, 
        regId:"123512",
        firstName: 'Jon', 
        lastName: 'Snow', 
        age: 35,
        phone:"(665)121-5454",
        email:"jonsnow@gmail.com",
        address:"0912 Won Street, Alabama",
        city:"New York",
        code:"10001",
        access:"Admin"
    },
    { 
        id: 2, 
        regId:"123512",
        firstName: 'Cersei', 
        lastName: 'Lannister', 
        age: 42 ,
        phone:"(421)314-2288",
        email:"cerseilannister@gmail.com",
        address:"1234 Main Street, New York",
        city:"New York",
        code:"13151",
        access:"Admin"
    },
    { 
        id: 3, 
        regId:"413251",
        firstName: 'Jaime', 
        lastName: 'Lannister', 
        age: 45 ,
        phone:"(422)982-6739",
        email:"jaimelannister@gmail.com",
        address:"3333 Want Blvd, Estanza, NAY 42125",
        city:"New York",
        code:"87281",
        access:"Admin"
    },
    { 
        id: 4, 
        regId:"123512",
        firstName: 'Arya', 
        lastName: 'Stark', 
        age: 16 ,
        phone:"(921)425-6742",
        email:"anyastark@gmail.com",
        address:"1514 Main Street, New York",
        city:"New York",
        code:"15551",
        access:"Manager"
    },
    { 
        id: 5, 
        regId:"123512",
        firstName: 'Daenerys', 
        lastName: 'Targaryen', 
        age: 31 ,
        phone:"(421)445-1189",
        email:"daenerystargaryen@gmail.com",
        address:"11122 Welping Ave, Tenting, CD 21321",
        city:"Tenting",
        code:"14215",
        access:"Manager"
    },
    { 
        id: 6, 
        regId:"123512",
        firstName: "Ever", 
        lastName: 'Melisandre', 
        age: 150 ,
        phone:"(232)545-6483",
        email:"evermelisandre@gmail.com",
        address:"1234 Canvile Street, Esvazark, NY 10001",
        city:"Esvazark",
        code:"10001",
        access:"User"
    },
    { 
        id: 7, 
        regId:"123512",
        firstName: 'Ferrara', 
        lastName: 'Clifford', 
        age: 44 ,
        phone:"(543)124-0123",
        email:"ferraraclifford@gmail.com",
        address:"22215 Super Street, Everting, ZO 515234",
        city:"Evertin",
        code:"51523",
        access:"User"
    },
    { 
        id: 8, 
        regId:"512315",
        firstName: 'Rossini', 
        lastName: 'Frances', 
        age: 36 ,
        phone:"(222)444-5555",
        email:"rossinifrances@gmail.com",
        address:"4123 Ever Blvd, Wentington, AD 142213",
        city:"Esteras",
        code:"44215",
        access:"User"
    },
    { 
        id: 9, 
        regId:"928397",
        firstName: 'Harvey', 
        lastName: 'Roxie', 
        age: 65 ,
        phone:"(444)555-6239",
        email:"harveyroxie@gmail.com",
        address:"51234 Avery Street, Cantory, ND 212412",
        city:"Colunza",
        code:"11234",
        access:"User"
    },
    { 
        id: 10, 
        regId:"533215",
        firstName: 'Enteri', 
        lastName: 'Redack', 
        age: 42 ,
        phone:"(222)444-5555",
        email:"enteriredack@gmail.com",
        address:"4123 Easer Blvd, Wentington, AD 142213",
        city:"Esteras",
        code:"44215",
        access:"User"
    },
    { 
        id: 11, 
        regId:"921975",
        firstName: 'Steve', 
        lastName: 'Goodman', 
        age: 11 ,
        phone:"(444)555-6239",
        email:"stevegoodmane@gmail.com",
        address:"51234 Fiveton Street, CunFory, ND 212412",
        city:"Colunza",
        code:"13542",
        access:"User"
    },
]